package com.capg.util;

public interface AppConstants {

	public static final String CATEGORY_ID_NOT_FOUND_INFO = "THE GIVEN CATEGORY ID DOES NOT EXIST IN THE DATABASE";
	public static final String QUESTION_ID_NOT_FOUND_INFO = "THE GIVEN QUESTION ID DOES NOT EXIST IN THE DATABSE";
	public static final String CATEGORY_NAME_ALREADY_EXISTS_INFO = "THE GIVEN CATEGORY ALREADY EXISTS IN THE DATABASE";
}
